### ISSUE TITLE
How to replace each corefering mention  by the main mention in the associated cluster?

### ISSUE THREAD

**Issue by PrasenjitGiri** [shon-otmazgin/fastcoref#1]
Which module to use to get the resolved text after running the coreference module?

**Comment by shon-otmazgin** [comment]
Hello @PrasenjitGiri 

After running the `predict` function, the function returns a list of `CorefResult`objects. To get the text clusters for each input you can run:

```python
texts = ['this is text1', 'this is text2']
preds = model.predict(texts=texts)

for p in preds:
    clusters = p.get_clusters(as_strings=True)
    print(p.text)
    print(clusters)
```

**Comment by PrasenjitGiri** [comment]
This isnt replacing the text with the cluster head. Do you have a way of replacing the references with the cluster head in the original sentence ? This functionality was available in neuralcoref

**Comment by shon-otmazgin** [comment]
This is not natively supported by the library but you can do something like:

```python
texts = ["Lionel Messi is a champion. He is the the player to beat. He plays at a different level."]

model = FCoref(device='cuda:0')
preds = model.predict(texts=texts, max_tokens_in_batch=5000)

text = preds[0].text
clusters = preds[0].get_clusters(as_strings=False)
messi_cluster = clusters[0]

# you need to decide here who is the primary mention in the cluster
primary_messi_mention = messi_cluster[0]

for start, end in reversed(messi_cluster):
    # iterate with reserve to not change the indices.

    if (start, end) == primary_messi_mention:
        continue

    text = text[:start] + text[primary_messi_mention[0]:primary_messi_mention[1]] + text[end:]
print(text)

```
`> Lionel Messi is a champion. Lionel Messi is the the player to beat. Lionel Messi plays at a different level.`

**Comment by PrasenjitGiri** [comment]
Thank you for the suggestion and it works on small sentences. But when I'm running it across the larger text/file it is adding in the issue of substituting texts in between words. 
Also, what is the max tokens used for?

Here is the publicly available data on wikipedia 
A bank is a financial institution that accepts deposits from the public and creates a demand deposit while simultaneously making loans. Lending activities can be directly performed by the bank or indirectly through capital markets.

Because banks play an important role in financial stability and the economy of a country, most jurisdictions exercise a high degree of regulation over banks. Most countries have institutionalised a system known as fractional reserve banking, under which banks hold liquid assets equal to only a portion of their current liabilities. In addition to other regulations intended to ensure liquidity, banks are generally subject to minimum capital requirements based on an international set of capital standards, the Basel Accords.


Banks act as payment agents by conducting checking or current accounts for customers, paying cheques drawn by customers in the bank, and collecting cheques deposited to customers' current accounts. Banks also enable customer payments via other payment methods such as Automated Clearing House (ACH), Wire transfers or telegraphic transfer, EFTPOS, and automated teller machines (ATMs).

Banks borrow money by accepting funds deposited on current accounts, by accepting term deposits, and by issuing debt securities such as banknotes and bonds. Banks lend money by making advances to customers on current accounts, by making installment loans, and by investing in marketable debt securities and other forms of money lending.

Banks provide different payment services, and a bank account is considered indispensable by most businesses and individuals. Non-banks that provide payment services such as remittance companies are normally not considered as an adequate substitute for a bank account.

Banks issue new money when they make loans. In contemporary banking systems, regulators set a minimum level of reserve funds that banks must hold against the deposit liabilities created by the funding of these loans, in order to ensure that the banks can meet demands for payment of such deposits. These reserves can be acquired through the acceptance of new deposits, sale of other assets, or borrowing from other banks including the central bank.


A bank can generate revenue in a variety of different ways including interest, transaction fees and financial advice. Traditionally, the most significant method is via charging interest on the capital it lends out to customers. The bank profits from the difference between the level of interest it pays for deposits and other sources of funds, and the level of interest it charges in its lending activities.

This difference is referred to as the spread between the cost of funds and the loan interest rate. Historically, profitability from lending activities has been cyclical and dependent on the needs and strengths of loan customers and the stage of the economic cycle. Fees and financial advice constitute a more stable revenue stream and banks have therefore placed more emphasis on these revenue lines to smooth their financial performance.

In the past 20 years, banks have taken many measures to ensure that they remain profitable while responding to increasingly changing market conditions.

Merging banking, investment, and insurance functions allows traditional banks to respond to increasing consumer demands for "one-stop shopping" by enabling cross-selling of products (which, the banks hope, will also increase profitability).

Second, they have expanded the use of risk-based pricing from business lending to consumer lending, which means charging higher interest rates to those customers that are considered to be a higher credit risk and thus increased chance of default on loans. This helps to offset the losses from bad loans, lowers the price of loans to those who have better credit histories, and offers credit products to high risk customers who would otherwise be denied credit.

Third, they have sought to increase the methods of payment processing available to the general public and business clients. These products include debit cards, prepaid cards, smart cards, and credit cards. They make it easier for consumers to conveniently make transactions and smooth their consumption over time (in some countries with underdeveloped financial systems, it is still common to deal strictly in cash, including carrying suitcases filled with cash to purchase a home).


However, with the convenience of easy credit, there is also an increased risk that consumers will mismanage their financial resources and accumulate excessive debt. Banks make money from card products through interest charges and fees charged to cardholders, and transaction fees to retailers who accept the bank's credit and/or debit cards for payments.

This helps in making a profit and facilitates economic development as a whole.

Recently, as banks have been faced with pressure from fintechs, new and additional business models have been suggested such as freemium, monetisation of data, white-labeling of banking and payment applications, or the cross-selling of complementary products.


Banks are susceptible to many forms of risk which have triggered occasional systemic crises.These include liquidity risk (where many depositors may request withdrawals in excess of available funds), credit risk (the chance that those who owe money to the bank will not repay it), and interest rate risk (the possibility that the bank will become unprofitable, if rising interest rates force it to pay relatively more on its deposits than it receives on its loans).

Banking crises have developed many times throughout history when one or more risks have emerged for the banking sector as a whole. Prominent examples include the bank run that occurred during the Great Depression, the U.S. Savings and Loan crisis in the 1980s and early 1990s, the Japanese banking crisis during the 1990s, and the sub-prime mortgage crisis in the 2000s.

Currently, commercial banks are regulated in most jurisdictions by government entities and require a special bank license to operate.

Usually, the definition of the business of banking for the purposes of regulation is extended to include acceptance of deposits, even if they are not repayable to the customer's order – although money lending, by itself, is generally not included in the definition.

Unlike most other regulated industries, the regulator is typically also a participant in the market, being either publicly or privately governed central bank. Central banks also typically have a monopoly on the business of issuing banknotes. However, in some countries, this is not the case. In the UK, for example, the Financial Services Authority licenses banks, and some commercial banks (such as the Bank of Scotland) issue their own banknotes in addition to those issued by the Bank of England, the UK government's central bank.


Global headquarters of the Bank for International Settlements in Basel
Banking law is based on a contractual analysis of the relationship between the bank (defined above) and the customer – defined as any entity for which the bank agrees to conduct an account.

The law implies rights and obligations into this relationship as follows.

The bank account balance is the financial position between the bank and the customer: when the account is in credit, the bank owes the balance to the customer; when the account is overdrawn, the customer owes the balance to the bank.
The bank agrees to pay the customer's checks up to the amount standing to the credit of the customer's account, plus any agreed overdraft limit.
The bank may not pay from the customer's account without a mandate from the customer, e.g. a cheque drawn by the customer.
The bank agrees to promptly collect the cheques deposited to the customer's account as the customer's agent and to credit the proceeds to the customer's account.
And, the bank has a right to combine the customer's accounts since each account is just an aspect of the same credit relationship.
The bank has a lien on cheques deposited to the customer's account, to the extent that the customer is indebted to the bank.
The bank must not disclose details of transactions through the customer's account – unless the customer consents, there is a public duty to disclose, the bank's interests require it, or the law demands it.
The bank must not close a customer's account without reasonable notice, since cheques are outstanding in the ordinary course of business for several days.
These implied contractual terms may be modified by express agreement between the customer and the bank. The statutes and regulations in force within a particular jurisdiction may also modify the above terms and/or create new rights, obligations, or limitations relevant to the bank-customer relationship.

Some types of financial institutions, such as building societies and credit unions, may be partly or wholly exempt from bank license requirements, and therefore regulated under separate rules.

The impact of the pandemic was higher for households that depended on labour income
For most households, the perception of changes in the financial situation is closely related to changes in income resulting
from the pandemic. From total households in Portugal, 27% indicated that they had a reduction in income between
2019 and 2020 due to the pandemic, 71% indicated that they had no income changes and 2% indicated an increase in
income.
Reductions in income due to the pandemic were less frequent in lower income households than in other income classes,
which may be related to the lower participation of these households in the labour market (Chart 2a and Table A2). In
the first income quintile, in which only 21% of the households’ reference person was working before the pandemic,
largely because in this quintile households with retired people predominate, 16% of the households indicated that they
had reductions in income due to the pandemic. In the highest income quintiles, in which in more than 70% of households
the reference person was working before the pandemic, the percentage of households that reported a reduction in
income was much higher (about 35% in the third and fourth quintiles).

And the modified python code

from fastcoref  import FCoref


class FastCoref():
    """Wrapper for FCoref
        https://github.com/shon-otmazgin/fastcoref
    """
    def __init__(self, text:list) -> None:
        """_summary_

        Args:
            text (list): Pass the texts in a list for coreference resolution
        """
        self.text = text
        self.model = FCoref()
        self.preds = self.model.predict(self.text, max_tokens_in_batch=5000)

    def resolve(self):
        """_summary_

        Returns:
            string: Coreference resolved text
        """
        text = self.preds[0].text

        clusters = self.preds[0].get_clusters(as_strings=False)

        for cluster in reversed(clusters):
            primary_mention = cluster[0]
            for start, end in reversed(cluster):
                if (start, end) == primary_mention:
                    continue

                text = text[:start] + text[primary_mention[0]:primary_mention[1]] + text[end:]

        return text

**Comment by shon-otmazgin** [comment]
I didn't test my solution, I just wanted to give you a hint on how to solve it, again, this is a custom behavior for your needs, the package is not natively supported for that replacement.

**Comment by shon-otmazgin** [comment]
in version `2.0.1` we have now `spacy_component` which supports your request:
do `pip install --upgrade fastcoref`


```python
from fastcoref import spacy_component
import spacy


text = 'Alice goes down the rabbit hole. Where she would discover a new reality beyond her expectations.'

nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("fastcoref")

doc = nlp(text)
doc._.coref_clusters
> [[(0, 5), (39, 42), (79, 82)]]
```

**Note**: it is better to `exclude=["parser", "lemmatizer", "ner", "textcat"]` at `spacy.load` since the component only rely on pos tagging.


You can also load other models, e.g. the more accurate model `LingMessCoref`:

```python
nlp.add_pipe(
   "fastcoref", 
   config={'model_architecture': 'LingMessCoref', 'model_path': 'biu-nlp/lingmess-coref', 'device': 'cpu'}
)
```

By specifying `resolve_text=True` in the pipe call, you can get the resolved text for each cluster:

```python
docs = nlp.pipe(
   texts, 
   component_cfg={"fastcoref": {'resolve_text': True}}
)

docs[0]._.resolved_text
> "Alice goes down the rabbit hole. Where Alice would discover a new reality beyond Alice's expectations."
```

**Comment by PrasenjitGiri** [comment]
Thank you for bringing in the update. I will do an extensive test. 
But, will like to add the "docs" is a generator and must be converted to list prior to accessing it via index. The above example does not work out of the box.

doc_list = list(docs)
print(doc_list[0]._.resolved_text)

**Comment by elmekkiMalek** [comment]
@PrasenjitGiri have you fixed the error of generator ?

**Comment by appledora** [comment]
@elmekkiMalek , the output is a generator by default. To access generator, you need to convert the output to a list, as @PrasenjitGiri demonstrated in his last reply :smiley:

**Comment by appledora** [comment]
`print(doc_list[0]._.resolved_text)`

Does this mean the model will work on a sentence level, only? 
@shon-otmazgin
