### ISSUE TITLE
dateutil: No module named 'dateutil'

### ISSUE THREAD

**Issue by nepp1d0** [shon-otmazgin/fastcoref#19]
Hi, 
I am trying to use fastcoref library but I got the following error as soon as I write `from fastcoref import FCoref`.
The error is:
`ImportError: Unable to import required dependencies:
dateutil: No module named 'dateutil'
`
I am running on Windows in a poetry environment with python 3.8 with no GPU. I tried installing `pip install python-dateutil` with no success as nothing changed. 

Any help would be much appreciated, I can provide more information like the stack trace if needed. 
Thanks in advance!

**Comment by shon-otmazgin** [comment]
Hello,

I don't know exactly what is your installed packages in the environment. You can create new environment with `venv` or `conda` and then install `fastcoref` ?

**Comment by nepp1d0** [comment]
Sorry if I did not tried it first, it seems to work as expected, so guess it is a compatibility problem with my environment. I'll try to figure it out then, but just in case there is a chance you can help me spotting the problem I attach here my environment infos and package installed. Thank you very much !

      $ poetry env info 
      Virtualenv
      Python:         3.8.10
      Implementation: CPython
      Path:           C:\Users\myUser\Documents\Source\g-core\.venv
      Executable:     C:\Users\myUser\Documents\Source\g-core\.venv\Scripts\python.exe
      Valid:          True
      
      System
      Platform:   win32
      OS:         nt
      Python:     3.8.10
      Path:       c:\python38
      Executable: c:\python38\python.exe

      $ pip install fastcoref
      WARNING: Ignoring invalid distribution -yrsistent (c:\users\myUser\documents\source\g-core\.venv\lib\site-packages)
      WARNING: Ignoring invalid distribution -yrsistent (c:\users\myUser\documents\source\g-core\.venv\lib\site-packages)
      Requirement already satisfied: fastcoref in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (2.1.1)
      Requirement already satisfied: torch>=1.10.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (1.12.1)
      Requirement already satisfied: transformers>=4.11.3 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (4.25.1)
      Requirement already satisfied: numpy>=1.21.6 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (1.23.5)
      Requirement already satisfied: datasets>=2.5.2 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (2.8.0)
      Requirement already satisfied: tqdm>=4.64.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (4.64.1)
      Requirement already satisfied: wandb>=0.13.4 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (0.13.7)
      Requirement already satisfied: spacy>=3.0.6 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (3.4.4)
      Requirement already satisfied: scipy>=1.7.3 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from fastcoref) (1.10.0)
      Requirement already satisfied: dill<0.3.7 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (0.3.6)
      Requirement already satisfied: pyyaml>=5.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (6.0)
      Requirement already satisfied: multiprocess in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (0.70.14)
      Requirement already satisfied: requests>=2.19.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (2.28.1)
      Requirement already satisfied: aiohttp in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (3.8.3)
      Requirement already satisfied: packaging in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (23.0)
      Requirement already satisfied: pandas in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (1.5.2)
      Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (0.11.1)
      Requirement already satisfied: pyarrow>=6.0.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (10.0.1)
      Requirement already satisfied: fsspec[http]>=2021.11.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (2022.11.0)
      Requirement already satisfied: xxhash in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (3.2.0)
      Requirement already satisfied: responses<0.19 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from datasets>=2.5.2->fastcoref) (0.18.0)
      Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (1.0.4)
      Requirement already satisfied: thinc<8.2.0,>=8.1.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (8.1.6)
      Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (1.0.9)
      Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (3.0.8)
      Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.10 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (3.0.11)
      Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (1.10.4)
      Requirement already satisfied: jinja2 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (3.1.2)
      Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (2.0.7)
      Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (3.3.0)
      Requirement already satisfied: setuptools in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (65.6.3)
      Requirement already satisfied: pathy>=0.3.5 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (0.10.1)
      Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (0.10.1)
      Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (6.3.0)
      Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (2.4.5)
      Requirement already satisfied: typer<0.8.0,>=0.3.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (0.7.0)
      Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from spacy>=3.0.6->fastcoref) (2.0.8)
      Requirement already satisfied: typing-extensions in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from torch>=1.10.0->fastcoref) (4.4.0)
      Requirement already satisfied: colorama in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from tqdm>=4.64.0->fastcoref) (0.4.6)
      Requirement already satisfied: regex!=2019.12.17 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from transformers>=4.11.3->fastcoref) (2022.10.31)
      Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from transformers>=4.11.3->fastcoref) (0.13.2)
      Requirement already satisfied: filelock in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from transformers>=4.11.3->fastcoref) (3.9.0)
      Requirement already satisfied: promise<3,>=2.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (2.3)
      Requirement already satisfied: GitPython>=1.0.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (3.1.30)
      Requirement already satisfied: pathtools in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (0.1.2)
      Requirement already satisfied: sentry-sdk>=1.0.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (1.12.1)
      Requirement already satisfied: setproctitle in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (1.3.2)
      Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (4.21.12)
      Requirement already satisfied: docker-pycreds>=0.4.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (0.4.0)
      Requirement already satisfied: Click!=8.0.0,>=7.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (8.1.3)
      Requirement already satisfied: psutil>=5.0.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (5.9.4)
      Requirement already satisfied: shortuuid>=0.5.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from wandb>=0.13.4->fastcoref) (1.0.11)
      Requirement already satisfied: six>=1.4.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from docker-pycreds>=0.4.0->wandb>=0.13.4->fastcoref) (1.16.0)
      Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (2.1.1)
      Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (6.0.4)
      Requirement already satisfied: frozenlist>=1.1.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (1.3.3)
      Requirement already satisfied: attrs>=17.3.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (22.2.0)
      Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (4.0.2)
      Requirement already satisfied: aiosignal>=1.1.2 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (1.3.1)
      Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from aiohttp->datasets>=2.5.2->fastcoref) (1.8.2)
      Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from GitPython>=1.0.0->wandb>=0.13.4->fastcoref) (4.0.10)
      Requirement already satisfied: idna<4,>=2.5 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from requests>=2.19.0->datasets>=2.5.2->fastcoref) (3.4)
      Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from requests>=2.19.0->datasets>=2.5.2->fastcoref) (1.26.13)
      Requirement already satisfied: certifi>=2017.4.17 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from requests>=2.19.0->datasets>=2.5.2->fastcoref) (2022.12.7)
      Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from thinc<8.2.0,>=8.1.0->spacy>=3.0.6->fastcoref) (0.0.3)
      Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from thinc<8.2.0,>=8.1.0->spacy>=3.0.6->fastcoref) (0.7.9)
      Requirement already satisfied: MarkupSafe>=2.0 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from jinja2->spacy>=3.0.6->fastcoref) (2.1.1)
      Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from pandas->datasets>=2.5.2->fastcoref) (2.8.2)
      Requirement already satisfied: pytz>=2020.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from pandas->datasets>=2.5.2->fastcoref) (2022.7)
      Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\myUser\documents\source\g-core\.venv\lib\site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb>=0.13.4->fastcoref) (5.0.0)

**Comment by nepp1d0** [comment]
Ok I'll close this issue since I found out my environment was corrupted, sorry for bother. Thank you very much for the help!
