### ISSUE TITLE
doc._.resolved_text does not work

### ISSUE THREAD

**Issue by reuvenlivn** [shon-otmazgin/fastcoref#20]
use in 
python 3.9.1
spacy 3.4.1
fastcoref 2.1.1

from fastcoref import spacy_component
import spacy
nlp = spacy.load("en_core_web_sm",exclude=["parser", "lemmatizer", "ner", "textcat"])
    
nlp.add_pipe("fastcoref",
       config={'model_architecture': 'LingMessCoref', 'model_path': 'biu-nlp/lingmess-coref', 'device': 'cpu'})
doc = nlp.pipe(text, component_cfg={"fastcoref": {'resolve_text': True}}) 
print(doc._.resolved_text)
******* AttributeError: 'generator' object has no attribute '_'****

**Comment by shon-otmazgin** [comment]
Hello @reuvenlivn 

please see https://github.com/shon-otmazgin/fastcoref/issues/18

**Comment by reuvenlivn** [comment]
thanks
