### ISSUE TITLE
Performing Coreference Resolution with Pre-Extracted Entity Mentions

### ISSUE THREAD

**Issue by laituan245** [shon-otmazgin/fastcoref#28]
In the quickstart example, the model handles both mention extraction and coreference resolution tasks. However, for my specific use case, I already have pre-extracted mentions available. Could you please guide me on how to perform coreference resolution exclusively, utilizing these existing mentions?

Thanks!

**Comment by shon-otmazgin** [comment]
Hello @laituan245 , as you mentioned, the package currently does 2 things, mention detection, then coref clusters for the extracted mentions. 

If you want to do only coref, this is a feature we need to develop, and you are welcome to support that if you wish so. 

In the meantime, I suggest you to compare if the exists mention detection component extract mention similar to what do you currently extracted. If so, no need to develop such thing...

**Comment by laituan245** [comment]
Thank you for your quick reply.
