### ISSUE TITLE
pip install fastcoref[train]    not working

### ISSUE THREAD

**Issue by shon-otmazgin** [shon-otmazgin/fastcoref#29]
@ariecattan @aryehgigi 

I released new version after the merges. not we have fastcoref 2.1.3 on PypI. But, `pip install fastcoref[train]`     dosent work

**Comment by aryehgigi** [comment]
for me it works..
![image](https://user-images.githubusercontent.com/5661975/232404293-9b69a6b9-2937-4a29-abb9-ad86fbeb68c5.png)
![image](https://user-images.githubusercontent.com/5661975/232404330-92f1fc11-e476-445f-882c-36b9929723eb.png)

**Comment by shon-otmazgin** [comment]
@aryehgigi  what I am doing wrong?

![image](https://user-images.githubusercontent.com/17564565/232407500-8f5d0f16-5a56-4eaf-b8d2-7c5adcea97fe.png)

**Comment by aryehgigi** [comment]
i think its because you are using zsh, try adding quots:
`pip install 'fastcoref[train]'`
and see [this answer](https://stackoverflow.com/a/30539963) for full explaination

**Comment by shon-otmazgin** [comment]
works ! thanks!!
