### ISSUE TITLE
no module names datasets error, what is the error and it is supported python 3.9?

### ISSUE THREAD

**Issue by SavitaKumariPandit** [shon-otmazgin/fastcoref#3]
hi  shon-otmazgin

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from fastcoref import FCoref
  File "/home/fastcoref/fastcoref/__init__.py", line 1, in <module>
    from .f_coref import FCoref, LingMessCoref
  File "/home/fastcoref/fastcoref/f_coref.py", line 8, in <module>
    from datasets import Dataset
ModuleNotFoundError: No module named 'datasets'

**Comment by shon-otmazgin** [comment]
Did you `pip install fastcoref` ?

**Comment by SavitaKumariPandit** [comment]
> hi shon-otmazgin

yes I have install fastcoref, I currently working with python version 3.9 there is some package installation issue  but now its working properly. Thanks for the contribution
