### ISSUE TITLE
trainer does not work for LingMeshCoref models

### ISSUE THREAD

**Issue by davidberenstein1957** [shon-otmazgin/fastcoref#38]
Hi, 

I wanted to train a model but by default, it uses FCoref models. Is there a specific reason for this?

Cheers,
David

**Comment by shon-otmazgin** [comment]
Yes, the goal of the package is for training a **fast** coreference model, we used LingMess as an annotator for unlabeled data.

if you want to train LingMess, you can use https://github.com/shon-otmazgin/lingmess-coref.

**Comment by davidberenstein1957** [comment]
Awesome, thank you!
