### ISSUE TITLE
Returned preds are not correlated with the input

### ISSUE THREAD

**Issue by aryehgigi** [shon-otmazgin/fastcoref#4]
Hey Shon, very cool work thanks!
Im working with @yoavg and wanted to experiment with the fastcoref..
I think there is a BUG with the order of the returned preds.

```python
from fastcoref import FCoref
model = FCoref()
preds = model.predict(texts=[p1, p2, p3])
print(p1)
print(p2)
print(p3)
print(preds[0])
print(preds[1])
print(preds[2])
```
as you can see, p1 is not correlated to preds[0] and so on..
is it fixable?

thanks again

screenshot:
![image](https://user-images.githubusercontent.com/5661975/194424974-7315d6a1-37d9-4df6-bc7c-c1382a66af8f.png)

**Comment by shon-otmazgin** [comment]
Hi @aryehgigi , 
This is right, we process the input in a different order to achieve better efficiency.
This is why each `pred` object has a `text` attribute in addition to the `clusters` attribute as you can see in your screenshot.

This is sloving your problem?

Shon

**Comment by aryehgigi** [comment]
Thanks for the answer @shon-otmazgin
i understand what you mean. Anyway i think it is a pitfall since users might assume that the order is the same as in the input (just like happened to me).
Think that anybody using this will need to match the input to the output in order for the output to be useful/meaningful, so adding this fix to your output (instead of letting the user do it) can be beneficial and less prone to failure.

If you are interested and i can try to add a PR for this, wdyt?

**Comment by shon-otmazgin** [comment]
@aryehgigi I saw your comment in. the PR - https://github.com/shon-otmazgin/fastcoref/pull/6. we will address it in the next release (which should be very soon). Thanks again for your input :)

**Comment by shon-otmazgin** [comment]
addressed in https://github.com/shon-otmazgin/fastcoref/pull/6
