### ISSUE TITLE
Spacy component

### ISSUE THREAD

**Issue by mlostar** [shon-otmazgin/fastcoref#5]
Hello,
Thanks for the amazing package. I have recently used it in one of my projects with great results. I believe there's currently a lack of coreference resolvers for Spacy3. Most of the packages I tried either don't work with Spacy3 or had worse results than this package. An official coreference resolver was added recently however it's still in experimental stage. So I believe there's merit to adding a spacy component that works out of the box using this package. I already have an implementation as I had to use this package together with spacy. If this is a desired feature I can clean up the implementation and send in a pull request.

**Comment by shon-otmazgin** [comment]
Hello @mlostar this is a great initiative! actually, @ariecattan also told me that this feature would be great and useful.

So this sounds great, open a PR and let's merge it!

**Comment by shon-otmazgin** [comment]
addressed in https://github.com/shon-otmazgin/fastcoref/pull/6
